### PR TITLE
Capetown-Class_1-Kudakwashe_Shambare-Javascript_Core_3-Week1

### PR DESCRIPTION
**Pull request by KudahShambare**
**Volunteers: Are you marking this coursework?** _You can find a guide on how to mark this coursework in `HOW_TO_MARK.md` in the root of this repository_

# Your Details

- Your Name: Kudakwashe  Shambare
- Your City:  Cape Town
- Your Slack Name: Kuda

# Homework Details

- Module:
- Week:

# Notes

- What did you find easy?
- Locating syntax errors

- What did you find hard?
- Locating logical errors

- What do you still not understand?

- Any other notes?

### CODE REVIEW

**Comment by douglas86** [comment]
Everything is running like it is suppose to. 10 out of 10 for this project.

**Comment by KudahShambare** [comment]
Thank you Douglas

**Comment by RyanS-Cpt** [comment]
Very nice Kuda, clean and efficient code

**Comment by KudahShambare** [comment]
Thank you Ryan.

**Pull request closed without merging**
